export const FETCH_COMPANIES_REQUEST = 'FETCH_COMPANIES_REQUEST'
export const FETCH_COMPANIES_SUCCESS = 'FETCH_COMPANIES_SUCCESS'
export const FETCH_COMPANIES_FAILURE = 'FETCH_COMPANIES_FAILURE'

export const FETCH_COMPANY_REQUEST = 'FETCH_COMPANY_REQUEST'
export const FETCH_COMPANY_SUCCESS = 'FETCH_COMPANY_SUCCESS'
export const FETCH_COMPANY_FAILURE = 'FETCH_COMPANY_FAILURE'

export const ADD_COMPANY_REQUEST = 'ADD_COMPANY_REQUEST'
export const ADD_COMPANY_SUCCESS = 'ADD_COMPANY_SUCCESS'
export const ADD_COMPANY_FAILURE = 'ADD_COMPANY_FAILURE'

export const EDIT_COMPANY_REQUEST = 'EDIT_COMPANY_REQUEST'
export const EDIT_COMPANY_SUCCESS = 'EDIT_COMPANY_SUCCESS'
export const EDIT_COMPANY_FAILURE = 'EDIT_COMPANY_FAILURE'

export const DELETE_COMPANY_REQUEST = 'DELETE_COMPANY_REQUEST'
export const DELETE_COMPANY_SUCCESS = 'DELETE_COMPANY_SUCCESS'
export const DELETE_COMPANY_FAILURE = 'DELETE_COMPANY_FAILURE'

export const ALL_COMPANIES_REQUEST = 'ALL_COMPANIES_REQUEST'
export const ALL_COMPANIES_SUCCESS = 'All_COMPANIES_SUCCESS'
export const ALL_COMPANIES_FAILURE = 'All_COMPANIES_FAILURE'
