export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE'

export const LOGIN_REQUEST = 'REGISTRATION_REQUEST'
export const LOGIN_SUCCESS = 'REGISTRATION_SUCCESS'
export const LOGIN_FAILURE = 'REGISTRATION_FAILURE'
